//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen ../../deps/schema.xsd -n Autostart -o Programs.cs
namespace Application.XmlSchemas;


/// <summary>
/// <para>Список всех доступных программ.</para>
/// </summary>
[System.ComponentModel.DescriptionAttribute("Список всех доступных программ.")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute("ProgramsType", Namespace = "")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ProgramsType
{

	[System.Xml.Serialization.XmlIgnoreAttribute()]
	private System.Collections.ObjectModel.Collection<ProgramType> _program;

	[System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
	[System.Xml.Serialization.XmlElementAttribute("Program")]
	public System.Collections.ObjectModel.Collection<ProgramType> Program
	{
		get
		{
			return _program;
		}
		private set
		{
			_program = value;
		}
	}

	/// <summary>
	/// <para xml:lang="en">Initializes a new instance of the <see cref="ProgramsType" /> class.</para>
	/// </summary>
	public ProgramsType()
	{
		this._program = new System.Collections.ObjectModel.Collection<ProgramType>();
	}
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute("ProgramType", Namespace = "")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ProgramType
{

	[System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
	[System.Xml.Serialization.XmlElementAttribute("Uri")]
	public string Uri { get; set; }

	[System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
	[System.Xml.Serialization.XmlElementAttribute("UriType")]
	public UriTypeEnum UriType { get; set; }

	[System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
	[System.Xml.Serialization.XmlElementAttribute("Name")]
	public string Name { get; set; }
}

/// <summary>
/// <para>Тип пути: Link — ярлык, Steam — игра в Steam, Browser — ссылка, открываемая в браузере.</para>
/// </summary>
[System.ComponentModel.DescriptionAttribute(("Тип пути: Link — ярлык, Steam — игра в Steam, Browser — ссылка, открываемая в бра" +
	"узере."))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute("UriTypeEnum", Namespace = "")]
public enum UriTypeEnum
{

	Link,

	Steam,

	Browser,
}

/// <summary>
/// <para>Коллекция проектов.</para>
/// </summary>
[System.ComponentModel.DescriptionAttribute("Коллекция проектов.")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute("ProjectsType", Namespace = "")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ProjectsType
{

	[System.Xml.Serialization.XmlIgnoreAttribute()]
	private System.Collections.ObjectModel.Collection<ProjectType> _project;

	[System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
	[System.Xml.Serialization.XmlElementAttribute("Project")]
	public System.Collections.ObjectModel.Collection<ProjectType> Project
	{
		get
		{
			return _project;
		}
		private set
		{
			_project = value;
		}
	}

	/// <summary>
	/// <para xml:lang="en">Initializes a new instance of the <see cref="ProjectsType" /> class.</para>
	/// </summary>
	public ProjectsType()
	{
		this._project = new System.Collections.ObjectModel.Collection<ProjectType>();
	}
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute("ProjectType", Namespace = "")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ProjectType
{

	[System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
	[System.Xml.Serialization.XmlElementAttribute("Name")]
	public string Name { get; set; }

	[System.Xml.Serialization.XmlIgnoreAttribute()]
	private System.Collections.ObjectModel.Collection<string> _start;

	[System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
	[System.Xml.Serialization.XmlArrayAttribute("Start")]
	[System.Xml.Serialization.XmlArrayItemAttribute("ProgramName")]
	public System.Collections.ObjectModel.Collection<string> Start
	{
		get
		{
			return _start;
		}
		private set
		{
			_start = value;
		}
	}

	/// <summary>
	/// <para xml:lang="en">Initializes a new instance of the <see cref="ProjectType" /> class.</para>
	/// </summary>
	public ProjectType()
	{
		this._start = new System.Collections.ObjectModel.Collection<string>();
	}
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute("StartListType", Namespace = "")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class StartListType
{

	[System.Xml.Serialization.XmlIgnoreAttribute()]
	private System.Collections.ObjectModel.Collection<string> _programName;

	[System.Xml.Serialization.XmlElementAttribute("ProgramName")]
	public System.Collections.ObjectModel.Collection<string> ProgramName
	{
		get
		{
			return _programName;
		}
		private set
		{
			_programName = value;
		}
	}

	/// <summary>
	/// <para xml:lang="en">Gets a value indicating whether the ProgramName collection is empty.</para>
	/// </summary>
	[System.Xml.Serialization.XmlIgnoreAttribute()]
	public bool ProgramNameSpecified
	{
		get
		{
			return (this.ProgramName.Count != 0);
		}
	}

	/// <summary>
	/// <para xml:lang="en">Initializes a new instance of the <see cref="StartListType" /> class.</para>
	/// </summary>
	public StartListType()
	{
		this._programName = new System.Collections.ObjectModel.Collection<string>();
	}
}

/// <summary>
/// <para>Главный элемент, содержащий коллекции программ и проектов.</para>
/// </summary>
[System.ComponentModel.DescriptionAttribute("Главный элемент, содержащий коллекции программ и проектов.")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute("Configuration", Namespace = "", AnonymousType = true)]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("Configuration", Namespace = "")]
public partial class Configuration
{

	[System.Xml.Serialization.XmlIgnoreAttribute()]
	private System.Collections.ObjectModel.Collection<ProgramType> _programs;

	[System.Xml.Serialization.XmlArrayAttribute("Programs")]
	[System.Xml.Serialization.XmlArrayItemAttribute("Program")]
	public System.Collections.ObjectModel.Collection<ProgramType> Programs
	{
		get
		{
			return _programs;
		}
		private set
		{
			_programs = value;
		}
	}

	/// <summary>
	/// <para xml:lang="en">Gets a value indicating whether the Programs collection is empty.</para>
	/// </summary>
	[System.Xml.Serialization.XmlIgnoreAttribute()]
	public bool ProgramsSpecified
	{
		get
		{
			return (this.Programs.Count != 0);
		}
	}

	/// <summary>
	/// <para xml:lang="en">Initializes a new instance of the <see cref="Configuration" /> class.</para>
	/// </summary>
	public Configuration()
	{
		this._programs = new System.Collections.ObjectModel.Collection<ProgramType>();
		this._projects = new System.Collections.ObjectModel.Collection<ProjectType>();
	}

	[System.Xml.Serialization.XmlIgnoreAttribute()]
	private System.Collections.ObjectModel.Collection<ProjectType> _projects;

	[System.Xml.Serialization.XmlArrayAttribute("Projects")]
	[System.Xml.Serialization.XmlArrayItemAttribute("Project")]
	public System.Collections.ObjectModel.Collection<ProjectType> Projects
	{
		get
		{
			return _projects;
		}
		private set
		{
			_projects = value;
		}
	}

	/// <summary>
	/// <para xml:lang="en">Gets a value indicating whether the Projects collection is empty.</para>
	/// </summary>
	[System.Xml.Serialization.XmlIgnoreAttribute()]
	public bool ProjectsSpecified
	{
		get
		{
			return (this.Projects.Count != 0);
		}
	}
}
